<?php
namespace app\admin\controller;


use extend\UploadImg;
use think\Exception;

class Banner extends AdminBase
{
    private $banner;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->banner = model('Banner');
    }

    //添加
    public function add()
    {
        if(request()->isPost()){
            $data = input();
            try{
                if(empty($data['name']))
                    throw new Exception('名称不能为空');

                if(empty($data['uploadImg']))
                    throw new Exception('上传图片不能为空');

                $year = date('Y/m',time());
                $re   = UploadImg::upload("banners/$year")->getMsg();
                $data['banner'] = "/banners/".$year."/".$re['info']['image'][0];
                unset($data['uploadImg']);
                //添加数据
                $add_data = array(
                    'name'  => $data['name'],
                    'image' => $data['banner']
                );
                $this->banner->save($add_data);

                Api()->setApi('url',0)->ApiSuccess();

            }catch (\Exception $e){
                Api()->setApi('msg',$e->getMessage())->setApi('url',url('index'))->ApiError();
            }
        }

        return view();



    }

    //列表
    public function index()
    {
        //用户列表
        $data = input();
        $banners = $this->banner->select_banner($data);
        return view(['banners'=>$banners]);
    }

    //删除
    public function del()
    {
        try{
            $data = input();
            if(empty($data['id']))
                throw new Exception('请选择要操作数据');
            $time = time();
            //用户信息
            $this->banner
                ->where('id','in',$data['id'])
                ->update(['delete_time'=>$time]);

            Api()->setApi('url',input('location'))->ApiSuccess();
        }catch(\Exception $e){
            Api()->setApi('msg',$e->getMessage())->setApi('url',0)->ApiError();
        }
    }
    
//    //预览
//    public function get_img()
//    {
//        $banner = $this->banner->where('id',input('id'))->value('image');
//        return view(['banner'=>$banner]);
//    }

    //改变状态
    public function status_set()
    {
        if(request()->isAjax()){
            try{
                $data = input();

                if(empty($data['id']))
                    throw new Exception('参数错误');
                switch ($data['status'])
                {
                    case 0:
                        $this->banner->where('id',$data['id'])->update(['status'=>1]);
                        break;
                    case 1:
                        $this->banner->where('id',$data['id'])->update(['status'=>0]);
                        break;

                }

               return json([
                   'status'   => true,
                   'msg'    => '操作成功'
               ]);

            }catch (\Exception $e){

                return json([
                    'status'  => false,
                    'msg'     => $e->getMessage()
                ]);
            }


        }
    }

}