<?php
namespace app\admin\controller;


class Member extends AdminBase
{
    private $member,$member_address;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->member = model('Member');
        $this->member_address = model('MemberAddress');

    }

    //添加
    public function edit()
    {
        if(request()->isPost()){
            $data = inpput();
        }else{
            //个人信息
            $id = input('id');
            if(!empty($id)){
                //会员信息
                $member = $this->member->find($id);
                $this->assign('data',$member);
                //会员地址
                $addresses = $this->member_address->where('member_id',$id)->select();
                $this->assign('addresses',$addresses);
            }

            return $this->fetch();

        }

    }

    //列表
    public function index()
    {
        //用户列表
        $data = input();
        $members = $this->member->select_member($data);
        return view(['lists'=>$members]);
    }

    //删除
    public function del()
    {
        try{
            $data = input();
            if(empty($data['id']))
                throw new Exception('请选择要操作数据');
            $time = time();
            //用户信息
            model('Member')
                ->where('id','in',$data['id'])
                ->update(['delete_time'=>$time]);
            //用户地址
            model('MemberAddress')
                ->where('member_id','in',$data['id'])
                ->update(['delete_time'=>$time]);

            Api()->setApi('url',input('location'))->ApiSuccess();
        }catch(\Exception $e){
            Api()->setApi('msg',$e->getMessage())->setApi('url',0)->ApiError();
        }
    }

}