<?php
namespace app\admin\controller;

use app\admin\model\Users;
use think\Exception;


class Opinion extends AdminBase
{
    private $opinion,$opinion_type;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->opinion      = model('opinion');
        $this->opinion_type = model('OpinionType');
    }

	//意见反馈记录列表
    public function index()
    {
        //反馈类型
        $types = $this->opinion_type->field('id,name')->select();
        //所有意见
        $data = input();
        $opinions = $this->opinion->select_opinion($data);
        return view([
            'types'      => $types,
            'lists'      => $opinions,
        ]);
    }

    //改变状态
    public function set_status()
    {
        if(request()->isPost()){
            $id     = input('id');
            $status = input('status');
            if(empty($id) || empty($status))
                Api()->setApi('msg','参数错误')->setApi('url',0)->ApiError();
            //改变状态
            $this->opinion->where('id',$id)->update(['status'=>$status]);

            Api()->setApi('url',input('location'))->ApiSuccess();
        }

    }

    public function opinion_type()
    {
        if(request()->isAjax()){
            $data = input();

            try{
                if(empty($data['id']))
                    throw new Exception('参数错误');
                if(empty($data['name']))
                    throw new Exception('请填写反馈类型名称');
                //更新意见类型
                $this->opinion_type->where('create_time','<',time())->delete();
                foreach ($data['id'] as $k => $v){
                    if(!empty($data['name'][$k])){
                        $this->opinion_type->isUpdate(false)->save(['id'=>$v,'name'=>$data['name'][$k]]);

                    }
                }
                Api()->setApi('url',input('location'))->ApiSuccess();
            }catch (\Exception $e){
                Api()->setApi('msg',$e->getMessage())->setApi('url',0)->ApiError();
            }

        }
        //所有类型
        $types = $this->opinion_type->order('id')->select();
        return view(['types'=>$types]);
    }

}