<?php
namespace app\admin\controller;


class Reserve extends AdminBase
{
    private $reserve;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->reserve= model('Reserve');
    }

    //列表
    public function index()
    {
        //预约列表
        $data = input();
        $reserves = $this->reserve->select_reserve($data);
        return view(['lists'=>$reserves]);
    }

//    //删除
//    public function del()
//    {
//        try{
//            $data = input();
//            if(empty($data['id']))
//                throw new Exception('请选择要操作数据');
//            $time = time();
//            //用户信息
//            model('Member')
//                ->where('id','in',$data['id'])
//                ->update(['delete_time'=>$time]);
//            //用户地址
//            model('MemberAddress')
//                ->where('member_id','in',$data['id'])
//                ->update(['delete_time'=>$time]);
//
//            Api()->setApi('url',input('location'))->ApiSuccess();
//        }catch(\Exception $e){
//            Api()->setApi('msg',$e->getMessage())->setApi('url',0)->ApiError();
//        }
//    }

}