<?php
/**
 * Created by PhpStorm.
 * User: tiway
 * Date: 2017/12/12
 * Time: 15:56
 */

namespace app\mobile\controller;


use think\Exception;

class Login extends MobileBase
{
    private $member;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        $this->member = model('Member');
    }

    public function get_sid()
    {
        $sid = session_id();
        return json($this->returnData(['id'=>$sid]));
    }

//

    public function sign_data()
    {

ini_set('error_reporting', -1);
ini_set('display_errors', -1);

header('Content-Type: text/html; charset=utf-8');


# openssl genrsa -out rsa_private_key.pem 1024
# openssl rsa -in rsa_private_key.pem -pubout -out rsa_public_key.pem

        $private_key = "-----BEGIN RSA PRIVATE KEY-----\n" .
            wordwrap(config('private_key'), 64, "\n", true) .
            "\n-----END RSA PRIVATE KEY-----";


$public_key = "-----BEGIN PUBLIC KEY-----\n" .
    wordwrap(config('public_key'), 64, "\n", true) .
    "\n-----END PUBLIC KEY-----";

$pi_key =  openssl_pkey_get_private($private_key);// 可用返回资源id
$pu_key = openssl_pkey_get_public($public_key);


// 加密数据
$data = array(
    'id' => '1234567890',
    'name' => '小明',
    'mobile' => '123456',
);
$data = json_encode($data);


$encrypted = '';
$decrypted = '';

openssl_public_encrypt($data, $encrypted, $pu_key);//公钥加密
$encrypted = base64_encode($encrypted);// base64传输
//echo $encrypted,"<br/>";


openssl_private_decrypt(base64_decode($encrypted), $decrypted, $pi_key);//私钥解密
echo $decrypted,"<br/>";


print_r(json_decode($decrypted, true));
    }
    
}