<?php
namespace app\mobile\controller;

use app\common\controller\Base;
use think\Session;

/**
 * Created by PhpStorm.
 * User: tiway
 * Date: 2017/12/12
 * Time: 15:35
 */
class MobileBase extends Base
{
    private $return_code = [
        '300'  => '未登录或登录过期',
        '400'  => '操作失败',
    ];

    protected $user_id;

    public function _initialize(){

        parent::_initialize(); // TODO: Change the autogenerated stub

        Session::init([
            'prefix'         => 'user',
            'type'           => '',
            'auto_start'     => false,//先关闭session
        ]);
        if (input('sid')) {
            session_id(input('sid'));
        }
        session_start();
        $this->user_id = session('user_id');

        header("Access-Control-Allow-Origin: *"); // 允许任意域名发起的跨域请求
        header('Access-Control-Allow-Headers: X-Requested-With,X_Requested_With');
    }

    public function returnData($data = [],$code = '', $msg = '')
    {
        $return_data = [
            'code' => empty($code) ? 500 : $code,
            'msg'  => empty($msg) ? '操作成功' : $msg,
            'data' => empty($data) ? [] : $data,
        ];
        if(!empty($msg)){
            $return_data['msg'] = $msg;
        }else if (isset($this->return_code[$code]) ) {
            $return_data['msg'] = $this->return_code[$code];
        }
        return $return_data;
    }

}